

const imageSchemaModel = require('../models/imageModel');


// Upload image
const uploadImage = async (req, res) => {

  try {

    // const image = new imageSchemaModel()
    //await image.save();

    const image = new imageSchemaModel({
      filename: req.file.filename,    //This is a unique name generated by Cloudinary
      path: req.file.path, // Cloudinary URL
      originalname: req.file.originalname,
    });

    await image.save();

    res.status(201).json({ message: 'Uploaded to Cloudinary!', image });
  }
  
  catch (err) {
    res.status(500).json({ error: err.message });
  }
};



// Get all images
const getImages = async (req, res) => {
  try {
    const images = await imageSchemaModel.find();  
    res.json(images);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// Delete image (only from DB, not Cloudinary unless you store public_id)
const deleteImage = async (req, res) => {
  try {
    const id = req.params.id;

    const deletedImage = await imageSchemaModel.findByIdAndDelete(id);

    if (!deletedImage) {
      return res.status(404).json({ message: 'Image not found' });
    }

    res.json({ message: 'Deleted from DB (not Cloudinary)' });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

module.exports = {
  uploadImage,
  getImages,
  deleteImage,
};






